### ISSUE TITLE
Does not build on macOS Monterey (12.2)

### ISSUE THREAD

**Issue by greeneg** [trwyant/perl-Mac-Pasteboard#2]
When running make, I get the following error:

```
cp lib/Mac/Pasteboard/Droplet.pod blib/lib/Mac/Pasteboard/Droplet.pod
cp lib/Mac/Pasteboard.pm blib/lib/Mac/Pasteboard.pm
Running Mkbootstrap for Pasteboard ()
chmod 644 "Pasteboard.bs"
"/opt/Perl/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- Pasteboard.bs blib/arch/auto/Mac/Pasteboard/Pasteboard.bs 644
make: *** No rule to make target 'Constant.PL', needed by 'constant-xs.inc'.  Stop.
```

Platform: macOS 12.2 build 21D48
Perl Version: 5.34.0
XCode: 13.2.1 build 13C100

**Comment by trwyant** [comment]
Thank you for letting me know. After looking into your issue I am not sure how versions 0.100 and 0.101 ever built on any version of macOS whatsoever, though I promise I did not release without seeing passing tests from CPAN testers. Not only that, but my "make a distribution" script runs target 'disttest', which also fails.

You should be able to get going again by deleting the last rule in the Makefile -- the one that reads

constant-c.inc constant-h.inc constant-xs.inc : Constant.PL
	$(PERLRUN) Constant.PL

Meantime I will figure out whether to include Constant.PL in the distribution or delete the rule.

**Comment by trwyant** [comment]
I just sent version 0.101_01 to PAUSE. This eliminates the extra rule, but also includes Constant.PL (moved to tools/) just in case it turns out to be needed.
